# Docker Compose for JSON Toolkit - Development Environment
# Use: docker-compose up

version: '3.8'

services:
  json-toolkit-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: json-toolkit-dev
    ports:
      - "3000:5173"
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./index.html:/app/index.html:ro
      # Exclude node_modules from volume mount
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    restart: unless-stopped
    networks:
      - json-toolkit-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  json-toolkit-network:
    driver: bridge